[project]
name = "apollo"
version = "0.2.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.2.5",
    "qutip>=5.1.1",
    "scipy>=1.15.2",
    "snntorch>=0.9.4",
    "torch>=2.9.0",
    "tqdm>=4.67.1",
]
